### ISSUE TITLE
启动服务报错，无法获取二维码

### ISSUE THREAD

**Issue by haichang** [wechaty/go-wechaty#133]
examples/ding-dong-bot.go
```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/wechaty/go-wechaty/wechaty"
	wp "github.com/wechaty/go-wechaty/wechaty-puppet"
	"github.com/wechaty/go-wechaty/wechaty-puppet/filebox"
	"github.com/wechaty/go-wechaty/wechaty-puppet/schemas"
	"github.com/wechaty/go-wechaty/wechaty/user"
)

func main() {
	var bot = wechaty.NewWechaty(wechaty.WithPuppetOption(wp.Option{
		Token: "",
	}))

	bot.OnScan(func(ctx *wechaty.Context, qrCode string, status schemas.ScanStatus, data string) {
		fmt.Printf("Scan QR Code to login: %v\nhttps://wechaty.github.io/qrcode/%s\n", status, qrCode)
	}).OnLogin(func(ctx *wechaty.Context, user *user.ContactSelf) {
		fmt.Printf("User %s logined\n", user.Name())
	}).OnMessage(onMessage).OnLogout(func(ctx *wechaty.Context, user *user.ContactSelf, reason string) {
		fmt.Printf("User %s logouted: %s\n", user, reason)
	})

	bot.DaemonStart()
}

func onMessage(ctx *wechaty.Context, message *user.Message) {
	log.Println(message)

	if message.Self() {
		log.Println("Message discarded because its outgoing")
		return
	}

	if message.Age() > 2*60*time.Second {
		log.Println("Message discarded because its TOO OLD(than 2 minutes)")
		return
	}

	if message.Type() != schemas.MessageTypeText || message.Text() != "#ding" {
		log.Println("Message discarded because it does not match #ding")
		return
	}

	// 1. reply text 'dong'
	_, err := message.Say("dong")
	if err != nil {
		log.Println(err)
		return
	}
	log.Println("REPLY with text: dong")

	// 2. reply image(qrcode image)
	fileBox := filebox.FromUrl("https://wechaty.github.io/wechaty/images/bot-qr-code.png")
	_, err = message.Say(fileBox)
	if err != nil {
		log.Println(err)
		return
	}

	log.Printf("REPLY with image: %s\n", fileBox)

	// 3. reply url link
	urlLink := user.NewUrlLink(&schemas.UrlLinkPayload{
		Description:  "Go Wechaty is a Conversational SDK for Chatbot Makers Written in Go",
		ThumbnailUrl: "https://wechaty.js.org/img/icon.png",
		Title:        "wechaty/go-wechaty",
		Url:          "https://github.com/wechaty/go-wechaty",
	})
	_, err = message.Say(urlLink)
	if err != nil {
		log.Println(err)
		return
	}
	log.Printf("REPLY with urlLink: %s\n", urlLink)
}

```

启动报错
```
[root@VM-92-9-centos /data/go-wechaty/examples]# WECHATY_LOG=verbose WECHATY_PUPPET=wechaty-puppet-service WECHATY_PUPPET_SERVICE_TOKEN=puppet_wxwork_xxxx WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true go run ding-dong-bot.go 
2022/05/24 11:34:15 PuppetService Start()
2022/05/24 11:34:21 puppet start err:  PuppetService Start() rejection: discoverServiceEndPoint() err: Get "https://api.chatie.io/v0/hosties/puppet_wxwork_xxxxxxxx": http: server gave HTTP response to HTTPS client
panic: PuppetService Start() rejection: discoverServiceEndPoint() err: Get "https://api.chatie.io/v0/hosties/puppet_wxwork_xxxxx": http: server gave HTTP response to HTTPS client

goroutine 1 [running]:
github.com/wechaty/go-wechaty/wechaty.(*Wechaty).DaemonStart(0xc0001ac240)
        /data/wechaty/go-wechaty/wechaty/wechaty.go:295 +0x126
main.main()
        /data/wechaty/go-wechaty/examples/ding-dong-bot.go:28 +0x13f
exit status 2
[root@VM-92-9-centos /data/wechaty/go-wechaty/examples]# WECHATY_LOG=verbose WECHATY_PUPPET=wechaty-puppet-service WECHATY_PUPPET_SERVICE_TOKEN=puppet_wxwork_xxxxx WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true go run ding-dong-bot.go 
2022/05/24 11:35:22 PuppetService Start()
2022/05/24 11:35:28 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"wxwork event trigger heartbeat event","timeout":120000}})
```

**Comment by dchaofei** [comment]
确保你的机器能正常访问 https://api.chatie.io/v0/hosties/puppet_wxwork_xxxxx

**Comment by haichang** [comment]
能正常访问，没有接收到扫码事件

![image](https://user-images.githubusercontent.com/19977173/170257016-954b7183-1eb8-4385-b3aa-69d7676f38e0.png)

**Comment by haichang** [comment]
puppet wxwork 的服务不是闭源的吗？

**Comment by dchaofei** [comment]
我怀疑这是 puppet-wxwork 的问题，你可以用 typescript 语言版本 wechaty 试试， 如果还是不行，就证实了我的说法，你只能联系 puppet-wxwork 相关维护人员帮忙看下了

**Comment by haichang** [comment]
上回应该是 puppet-wxwork服务有问题，现在可以返回二维码，但是扫码无法登陆
```
$ WECHATY_LOG=verbose WECHATY_PUPPET=wechaty-puppet-service WECHATY_PUPPET_SERVICE_TOKEN=puppet_wxwork_xxxxxxxx WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true go run ding-dong-bot.go
2022/05/31 17:17:55 PuppetService Start()
2022/05/31 17:17:57 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"Wechaty Puppet gRPC stream connect successfully"}})
2022/05/31 17:17:57 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=BEBBBA954874EB76E428E5D2A7188597&wx=1","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://wechaty.github.io/qrcode/https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=BEBBBA954874EB76E428E5D2A7188597&wx=1
2022/05/31 17:18:13 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"wxwork event trigger heartbeat
```

**Comment by dchaofei** [comment]
看起来二维码有问题，你可以升级最新的 examples/ding-dong-bot.go 试下吗？

**Comment by haichang** [comment]
升级后可以了，十分感谢
