### ISSUE TITLE
无法发送gif文件

### ISSUE THREAD

**Issue by qcgzxw** [wechaty/go-wechaty#136]
代码
```golang
// fileUrl := 'http://127.0.0.1:8000//public/uploads/images/2022/09/16/ea34c37f9fd64edb401ebc5939bab54a.gif'
if file := filebox.FromUrl(fileUrl); file.Error() != nil {
		err = file.Error()
	} else {
		err =room.Say(file)
	}
```
发送动图报错
```
rpc error: code = Unknown desc = Error: ERR_SEND_MSG can not send gif without url
    at Manager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\manager.js:1750:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\manager.js:28:58)
```

**Comment by dchaofei** [comment]
@qcgzxw 这应该是一个 puppet service 问题，你使用的是 wxwork puppet service，可以把 issue 发到 https://github.com/juzibot/wxwork-tester/issues 以获得解决办法

**Comment by dchaofei** [comment]
@qcgzxw 我今天用 wxwork puppet 发送了一个 gif，可以发的
```go
	f := filebox.FromUrl("https://img95.699pic.com/photo/40168/3647.gif_wh860.gif")
	_, e := message.Say(f)
	if e != nil {
		fmt.Println("ERRR----", e.Error())
	}
```
